name: Build kabi novel

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-push-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 7.x

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        env:
          npm_config_registry: https://registry.npmmirror.com

      - name: Build project
        run: pnpm run build
        env:
          NODE_ENV: production

      - name: Verify build
        run: |
          [ -d "dist" ] && [ "$(ls -A dist)" ] || { echo "Build failed - dist directory is empty"; exit 1; }

      - name: Commit and push dist files
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add dist/
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Auto-update: Build latest dist files"
            git push origin ${{ github.ref }}
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: build-${{ github.sha }}
          name: Build version ${{ github.sha }}
          body: "Automatically generated build from latest commit"
          files: dist/**/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
